spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:mysql://localhost:3306/db_articles_v1
    username: root
    password: Hermajesty123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update